### ISSUE TITLE
get_queries_left_for_today?token=invalid_token should return error XML/JSON

### ISSUE THREAD

**Issue by bzaar** [morpher-ru/Morpher.WebService.V3#23]
This query:

https://ws3.morpher.ru/get_queries_left_for_today?token=invalid_token

returns a blank page while it should return XML/JSON similar to this:

    <error xmlns="http://schemas.datacontract.org/2004/07/Morpher.WebService.V3.General.Data" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
        <code>10</code>
        <message>Неверный формат токена.</message>
    </error>

See e.g. https://ws3.morpher.ru/russian/declension?s=%D0%9F%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8C&token=invalid_token

See also http://morpher.ru/ws3/#errors

**Comment by bzaar** [comment]
It should also return HTTP status 400 Bad Request.

**Comment by my-official** [comment]
И с этим [PR](https://github.com/morpher-ru/Morpher.WebService.V3/pull/34) я не согласен, потому что [это](https://github.com/morpher-ru/Morpher.WebService.V3/pull/34/files#diff-d320d92ad1d166c26915cd3632a45b45), вообще говоря, ошибка. Например, russian/declension попытается выполниться, а этого делать нельзя, т.к. токена нет.
Кроме того, это довольно серьезное изменение, которое требует, чтобы endpoint'ы самостоятельно обрабатывали наличие ошибок на предыдущих уровнях.
А тест с исправленными замечаниями перенес для глобального режима.

PR: https://github.com/morpher-ru/Morpher.WebService.V3/pull/51
