### ISSUE TITLE
get_queries_left_for_today return error in Local mode

### ISSUE THREAD

**Issue by ilya34** [morpher-ru/Morpher.WebService.V3#26]
The query 
http://localhost:61414/get_queries_left_for_today?token=invalid_token 
returns error in Debug mode: 
An error occurred when trying to create a controller of type 'ServiceController'. Make sure that the controller has a parameterless public constructor.

In AutofacInit.cs in void RegisterLocal (for Local mode) were missing IApiThrottler, IMorpherLog, IMorpherDatabase, IMorpherCache that's needed for ServiceController.

**Comment by bzaar** [comment]
In Local mode it should just return 400 Bad Request.

**Comment by bzaar** [comment]
Алексей, давай добьем эту задачку. Вот начатый PR: #35.

**Comment by my-official** [comment]
Я не согласился с изменениями из того PR: ServiceController полностью относится к глобальному варианту сервиса и нет смысла даже компилировать его для локального варианта.

Если обработчик запроса отсутствует, то ASP.NET возвращает стандартную ошибку 40**4**, а не 400.

ws3 на хостинге также себя ведет.

Новый PR:
https://github.com/morpher-ru/Morpher.WebService.V3/pull/50
